In [6]:
import pypsa

n = pypsa.Network()

n.add("Bus", "zone_1")
n.add("Bus", "zone_2")
n.buses

,v_nom,type,x,y,carrier,unit,location,v_mag_pu_set,v_mag_pu_min,v_mag_pu_max,control,generator,sub_network
Bus,,,,,,,,,,,,,
zone_1,1.0,,0.0,0.0,AC,,,1.0,0.0,inf,PQ,,
zone_2,1.0,,0.0,0.0,AC,,,1.0,0.0,inf,PQ,,

In [7]:
n.add("Load", "load_1", bus="zone_1", p_set=500)
n.add("Load", "load_2", bus="zone_2", p_set=1500)
n.loads

           bus carrier type   p_set  q_set  sign  active
Load
load_1  zone_1                500.0    0.0  -1.0    True
load_2  zone_2               1500.0    0.0  -1.0    True

In [ ]:
n.add(
    "Generator",
    "gen_1",
    bus="zone_1",
    p_nom=2000,
    marginal_cost=10,
    marginal_cost_quadratic=0.005)

n.add(
    "Generator",
    "gen_2",
    bus="zone_2",
    p_nom=2000,
    marginal_cost=13,
    marginal_cost_quadratic=0.01)

n.generators

,bus,control,type,p_nom,p_nom_mod,p_nom_extendable,p_nom_min,p_nom_max,p_min_pu,p_max_pu,...,min_up_time,min_down_time,up_time_before,down_time_before,ramp_limit_up,ramp_limit_down,ramp_limit_start_up,ramp_limit_shut_down,weight,p_nom_opt
Generator,,,,,,,,,,,,,,,,,,,,,
gen_1,zone_1,PQ,,2000.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0
gen_2,zone_2,PQ,,2000.0,0.0,False,0.0,inf,0.0,1.0,...,0,0,1,0,NaN,NaN,1.0,1.0,1.0,0.0

In [9]:
n.add("Line", "line_1", bus0="zone_1", bus1="zone_2", x=0.01, s_nom=400)
n.lines

,bus0,bus1,type,x,r,g,b,s_nom,s_nom_mod,s_nom_extendable,...,v_ang_min,v_ang_max,sub_network,x_pu,r_pu,g_pu,b_pu,x_pu_eff,r_pu_eff,s_nom_opt
Line,,,,,,,,,,,,,,,,,,,,,
line_1,zone_1,zone_2,,0.01,0.0,0.0,0.0,400.0,0.0,False,...,-inf,inf,,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [10]:
n.optimize()

WARNING:pypsa.consistency:The following lines have carriers which are not defined:
Index(['line_1'], dtype='object', name='Line')
WARNING:pypsa.consistency:The following lines have zero r, which could break the linear load flow:
Index(['line_1'], dtype='object', name='Line')
WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['zone_1', 'zone_2'], dtype='object', name='Bus')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.02s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 3 primals, 8 duals
Objective: 3.94e+04
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Line-fix-s-lower, Line-fix-s-upper were not assigned to the network.

('ok', 'optimal')

In [11]:
n.generators_t.p

Generator  gen_1   gen_2
snapshot
now        900.0  1100.0

In [12]:
n.buses_t.marginal_price

Bus         zone_1    zone_2
snapshot
now       19.00009  35.00011

In [13]:
n.lines_t.p1

Line      line_1
snapshot
now       -400.0

In [15]:
n.buses_t.marginal_price.eval("zone_2 - zone_1") * n.lines_t.p0["line_1"]

snapshot
now    6400.008
dtype: float64

In [16]:
network = pypsa.Network()
network.import_from_pandapower_net(pandapower_ieee33_network)

NameError: name 'pandapower_ieee33_network' is not defined