In [43]:
import pypsa
import pandas as pd
import numpy as np

Parse the dataset (household)

In [44]:
csv_data = pd.read_csv("household_data_60min_singleindex.csv",
                       parse_dates=["utc_timestamp"],
                       index_col="utc_timestamp",
                       usecols=lambda col: "utc_timestamp" in col or ("residential" in col and ("grid_import" in col or "pv" in col)) or "residential" in col
                       )
print(csv_data.info())

<class 'pandas.DataFrame'>
DatetimeIndex: 38454 entries, 2014-12-11 17:00:00+00:00 to 2019-05-01 22:00:00+00:00
Data columns (total 39 columns):
 #   Column                               Non-Null Count  Dtype
---  ------                               --------------  -----
 0   DE_KN_residential1_dishwasher        15845 non-null  float64
 1   DE_KN_residential1_freezer           12896 non-null  float64
 2   DE_KN_residential1_grid_import       15873 non-null  float64
 3   DE_KN_residential1_heat_pump         15873 non-null  float64
 4   DE_KN_residential1_pv                15873 non-null  float64
 5   DE_KN_residential1_washing_machine   15846 non-null  float64
 6   DE_KN_residential2_circulation_pump  19823 non-null  float64
 7   DE_KN_residential2_dishwasher        19134 non-null  float64
 8   DE_KN_residential2_freezer           10251 non-null  float64
 9   DE_KN_residential2_grid_import       15798 non-null  float64
 10  DE_KN_residential2_washing_machine   24733 non-null  float64
 11  DE_KN_residential3_circulation_pump  33210 non-null  float64
 12  DE_KN_residential3_dishwasher        29097 non-null  float64
 13  DE_KN_residential3_freezer           28732 non-null  float64
 14  DE_KN_residential3_grid_export       22555 non-null  float64
 15  DE_KN_residential3_grid_import       11904 non-null  float64
 16  DE_KN_residential3_pv                22555 non-null  float64
 17  DE_KN_residential3_refrigerator      25101 non-null  float64
 18  DE_KN_residential3_washing_machine   30546 non-null  float64
 19  DE_KN_residential4_dishwasher        12620 non-null  float64
 20  DE_KN_residential4_ev                20288 non-null  float64
 21  DE_KN_residential4_freezer           20288 non-null  float64
 22  DE_KN_residential4_grid_export       20360 non-null  float64
 23  DE_KN_residential4_grid_import       20360 non-null  float64
 24  DE_KN_residential4_heat_pump         12311 non-null  float64
 25  DE_KN_residential4_pv                20360 non-null  float64
 26  DE_KN_residential4_refrigerator      10764 non-null  float64
 27  DE_KN_residential4_washing_machine   12258 non-null  float64
 28  DE_KN_residential5_dishwasher        23541 non-null  float64
 29  DE_KN_residential5_grid_import       30804 non-null  float64
 30  DE_KN_residential5_refrigerator      14564 non-null  float64
 31  DE_KN_residential5_washing_machine   23541 non-null  float64
 32  DE_KN_residential6_circulation_pump  21534 non-null  float64
 33  DE_KN_residential6_dishwasher        14061 non-null  float64
 34  DE_KN_residential6_freezer           15346 non-null  float64
 35  DE_KN_residential6_grid_export       16690 non-null  float64
 36  DE_KN_residential6_grid_import       21534 non-null  float64
 37  DE_KN_residential6_pv                21534 non-null  float64
 38  DE_KN_residential6_washing_machine   14784 non-null  float64
dtypes: float64(39)
memory usage: 11.7 MB
None

In [45]:
start_time = "2016-07-15 00:00:00"
end_time = "2016-07-15 23:00:00"
dataset_day = csv_data.loc[start_time:end_time]
print(dataset_day)


load_cols = [col for col in dataset_day.columns if "grid_import" in col]
pv_cols = [col for col in dataset_day.columns if "pv" in col ]

if (len(load_cols) == 0 or len(pv_cols) == 0):
    raise ValueError("Could not find consumption or solar columns")

print(f"Found {len(load_cols)} loads and {len(pv_cols)} pv")

                           DE_KN_residential1_dishwasher  \
utc_timestamp
2016-07-15 00:00:00+00:00                        189.028
2016-07-15 01:00:00+00:00                        189.028
2016-07-15 02:00:00+00:00                        189.028
2016-07-15 03:00:00+00:00                        189.028
2016-07-15 04:00:00+00:00                        189.028
2016-07-15 05:00:00+00:00                        189.028
2016-07-15 06:00:00+00:00                        189.028
2016-07-15 07:00:00+00:00                        189.028
2016-07-15 08:00:00+00:00                        189.028
2016-07-15 09:00:00+00:00                        189.028
2016-07-15 10:00:00+00:00                        189.028
2016-07-15 11:00:00+00:00                        189.028
2016-07-15 12:00:00+00:00                        189.028
2016-07-15 13:00:00+00:00                        189.028
2016-07-15 14:00:00+00:00                        189.028
2016-07-15 15:00:00+00:00                        189.028
2016-07-15 16:00:00+00:00                        189.028
2016-07-15 17:00:00+00:00                        189.028
2016-07-15 18:00:00+00:00                        189.028
2016-07-15 19:00:00+00:00                        189.028
2016-07-15 20:00:00+00:00                        189.028
2016-07-15 21:00:00+00:00                        189.028
2016-07-15 22:00:00+00:00                        189.028
2016-07-15 23:00:00+00:00                        189.028

                           DE_KN_residential1_freezer  \
utc_timestamp
2016-07-15 00:00:00+00:00                     235.373
2016-07-15 01:00:00+00:00                     235.409
2016-07-15 02:00:00+00:00                     235.441
2016-07-15 03:00:00+00:00                     235.482
2016-07-15 04:00:00+00:00                     235.518
2016-07-15 05:00:00+00:00                     235.548
2016-07-15 06:00:00+00:00                     235.586
2016-07-15 07:00:00+00:00                     235.628
2016-07-15 08:00:00+00:00                     235.665
2016-07-15 09:00:00+00:00                     235.697
2016-07-15 10:00:00+00:00                     235.730
2016-07-15 11:00:00+00:00                     235.773
2016-07-15 12:00:00+00:00                     235.810
2016-07-15 13:00:00+00:00                     235.842
2016-07-15 14:00:00+00:00                     235.875
2016-07-15 15:00:00+00:00                     235.927
2016-07-15 16:00:00+00:00                     235.962
2016-07-15 17:00:00+00:00                     235.998
2016-07-15 18:00:00+00:00                     236.040
2016-07-15 19:00:00+00:00                     236.084
2016-07-15 20:00:00+00:00                     236.118
2016-07-15 21:00:00+00:00                     236.154
2016-07-15 22:00:00+00:00                     236.199
2016-07-15 23:00:00+00:00                     236.232

                           DE_KN_residential1_grid_import  \
utc_timestamp
2016-07-15 00:00:00+00:00                        5676.017
2016-07-15 01:00:00+00:00                        5676.340
2016-07-15 02:00:00+00:00                        5676.648
2016-07-15 03:00:00+00:00                        5677.082
2016-07-15 04:00:00+00:00                        5677.599
2016-07-15 05:00:00+00:00                        5678.057
2016-07-15 06:00:00+00:00                        5678.407
2016-07-15 07:00:00+00:00                        5680.548
2016-07-15 08:00:00+00:00                        5681.225
2016-07-15 09:00:00+00:00                        5681.687
2016-07-15 10:00:00+00:00                        5682.116
2016-07-15 11:00:00+00:00                        5684.562
2016-07-15 12:00:00+00:00                        5686.257
2016-07-15 13:00:00+00:00                        5687.167
2016-07-15 14:00:00+00:00                        5687.757
2016-07-15 15:00:00+00:00                        5688.167
2016-07-15 16:00:00+00:00                        5688.557
2016-07-15 17:00:00+00:00                        5688.937
2016-07-15 18:00:00+00:00                        5689.392
2016-07-15 19:00:00+00:00                        5689.786
2016-07-15 20:00:00+00:00                        5690.187
2016-07-15 21:00:00+00:00                        5690.585
2016-07-15 22:00:00+00:00                        5691.137
2016-07-15 23:00:00+00:00                        5691.648

                           DE_KN_residential1_heat_pump  \
utc_timestamp
2016-07-15 00:00:00+00:00                      5348.218
2016-07-15 01:00:00+00:00                      5348.228
2016-07-15 02:00:00+00:00                      5348.247
2016-07-15 03:00:00+00:00                      5349.012
2016-07-15 04:00:00+00:00                      5350.737
2016-07-15 05:00:00+00:00                      5351.205
2016-07-15 06:00:00+00:00                      5351.558
2016-07-15 07:00:00+00:00                      5351.987
2016-07-15 08:00:00+00:00                      5351.997
2016-07-15 09:00:00+00:00                      5352.327
2016-07-15 10:00:00+00:00                      5352.337
2016-07-15 11:00:00+00:00                      5353.087
2016-07-15 12:00:00+00:00                      5353.097
2016-07-15 13:00:00+00:00                      5353.678
2016-07-15 14:00:00+00:00                      5354.897
2016-07-15 15:00:00+00:00                      5354.907
2016-07-15 16:00:00+00:00                      5355.427
2016-07-15 17:00:00+00:00                      5355.798
2016-07-15 18:00:00+00:00                      5356.603
2016-07-15 19:00:00+00:00                      5357.097
2016-07-15 20:00:00+00:00                      5357.912
2016-07-15 21:00:00+00:00                      5358.317
2016-07-15 22:00:00+00:00                      5359.638
2016-07-15 23:00:00+00:00                      5359.657

                           DE_KN_residential1_pv  \
utc_timestamp
2016-07-15 00:00:00+00:00              11778.905
2016-07-15 01:00:00+00:00              11778.905
2016-07-15 02:00:00+00:00              11778.905
2016-07-15 03:00:00+00:00              11778.905
2016-07-15 04:00:00+00:00              11778.942
2016-07-15 05:00:00+00:00              11779.378
2016-07-15 06:00:00+00:00              11780.782
2016-07-15 07:00:00+00:00              11783.745
2016-07-15 08:00:00+00:00              11789.221
2016-07-15 09:00:00+00:00              11792.944
2016-07-15 10:00:00+00:00              11795.116
2016-07-15 11:00:00+00:00              11799.040
2016-07-15 12:00:00+00:00              11802.076
2016-07-15 13:00:00+00:00              11803.514
2016-07-15 14:00:00+00:00              11805.289
2016-07-15 15:00:00+00:00              11806.769
2016-07-15 16:00:00+00:00              11807.207
2016-07-15 17:00:00+00:00              11807.771
2016-07-15 18:00:00+00:00              11807.895
2016-07-15 19:00:00+00:00              11807.897
2016-07-15 20:00:00+00:00              11807.897
2016-07-15 21:00:00+00:00              11807.897
2016-07-15 22:00:00+00:00              11807.897
2016-07-15 23:00:00+00:00              11807.897

                           DE_KN_residential1_washing_machine  \
utc_timestamp
2016-07-15 00:00:00+00:00                             201.294
2016-07-15 01:00:00+00:00                             201.296
2016-07-15 02:00:00+00:00                             201.298
2016-07-15 03:00:00+00:00                             201.300
2016-07-15 04:00:00+00:00                             201.303
2016-07-15 05:00:00+00:00                             201.303
2016-07-15 06:00:00+00:00                             201.305
2016-07-15 07:00:00+00:00                             201.305
2016-07-15 08:00:00+00:00                             201.305
2016-07-15 09:00:00+00:00                             201.305
2016-07-15 10:00:00+00:00                             201.306
2016-07-15 11:00:00+00:00                             201.820
2016-07-15 12:00:00+00:00                             201.863
2016-07-15 13:00:00+00:00                             201.865
2016-07-15 14:00:00+00:00                             201.867
2016-07-15 15:00:00+00:00                             201.867
2016-07-15 16:00:00+00:00                             201.867
2016-07-15 17:00:00+00:00                             201.867
2016-07-15 18:00:00+00:00                             201.867
2016-07-15 19:00:00+00:00                             201.867
2016-07-15 20:00:00+00:00                             201.867
2016-07-15 21:00:00+00:00                             201.867
2016-07-15 22:00:00+00:00                             201.868
2016-07-15 23:00:00+00:00                             201.868

                           DE_KN_residential2_circulation_pump  \
utc_timestamp
2016-07-15 00:00:00+00:00                              470.581
2016-07-15 01:00:00+00:00                              470.585
2016-07-15 02:00:00+00:00                              470.589
2016-07-15 03:00:00+00:00                              470.592
2016-07-15 04:00:00+00:00                              470.715
2016-07-15 05:00:00+00:00                              470.797
2016-07-15 06:00:00+00:00                              470.841
2016-07-15 07:00:00+00:00                              470.884
2016-07-15 08:00:00+00:00                              470.936
2016-07-15 09:00:00+00:00                              470.988
2016-07-15 10:00:00+00:00                              471.048
2016-07-15 11:00:00+00:00                              471.093
2016-07-15 12:00:00+00:00                              471.185
2016-07-15 13:00:00+00:00                              471.239
2016-07-15 14:00:00+00:00                              471.259
2016-07-15 15:00:00+00:00                              471.315
2016-07-15 16:00:00+00:00                              471.325
2016-07-15 17:00:00+00:00                              471.333
2016-07-15 18:00:00+00:00                              471.342
2016-07-15 19:00:00+00:00                              471.346
2016-07-15 20:00:00+00:00                              471.350
2016-07-15 21:00:00+00:00                              471.353
2016-07-15 22:00:00+00:00                              471.357
2016-07-15 23:00:00+00:00                              471.361

                           DE_KN_residential2_dishwasher  \
utc_timestamp
2016-07-15 00:00:00+00:00                        287.625
2016-07-15 01:00:00+00:00                        287.626
2016-07-15 02:00:00+00:00                        287.627
2016-07-15 03:00:00+00:00                        287.629
2016-07-15 04:00:00+00:00                        287.629
2016-07-15 05:00:00+00:00                        287.629
2016-07-15 06:00:00+00:00                        287.630
2016-07-15 07:00:00+00:00                        287.630
2016-07-15 08:00:00+00:00                        287.630
2016-07-15 09:00:00+00:00                        287.630
2016-07-15 10:00:00+00:00                        287.630
2016-07-15 11:00:00+00:00                        287.631
2016-07-15 12:00:00+00:00                        287.631
2016-07-15 13:00:00+00:00                        287.631
2016-07-15 14:00:00+00:00                        287.631
2016-07-15 15:00:00+00:00                        287.631
2016-07-15 16:00:00+00:00                        287.632
2016-07-15 17:00:00+00:00                        287.632
2016-07-15 18:00:00+00:00                        287.632
2016-07-15 19:00:00+00:00                        287.632
2016-07-15 20:00:00+00:00                        287.632
2016-07-15 21:00:00+00:00                        287.633
2016-07-15 22:00:00+00:00                        287.633
2016-07-15 23:00:00+00:00                        287.633

                           DE_KN_residential2_freezer  \
utc_timestamp
2016-07-15 00:00:00+00:00                         NaN
2016-07-15 01:00:00+00:00                         NaN
2016-07-15 02:00:00+00:00                         NaN
2016-07-15 03:00:00+00:00                         NaN
2016-07-15 04:00:00+00:00                         NaN
2016-07-15 05:00:00+00:00                         NaN
2016-07-15 06:00:00+00:00                         NaN
2016-07-15 07:00:00+00:00                         NaN
2016-07-15 08:00:00+00:00                         NaN
2016-07-15 09:00:00+00:00                         NaN
2016-07-15 10:00:00+00:00                         NaN
2016-07-15 11:00:00+00:00                         NaN
2016-07-15 12:00:00+00:00                         NaN
2016-07-15 13:00:00+00:00                         NaN
2016-07-15 14:00:00+00:00                         NaN
2016-07-15 15:00:00+00:00                         NaN
2016-07-15 16:00:00+00:00                         NaN
2016-07-15 17:00:00+00:00                         NaN
2016-07-15 18:00:00+00:00                         NaN
2016-07-15 19:00:00+00:00                         NaN
2016-07-15 20:00:00+00:00                         NaN
2016-07-15 21:00:00+00:00                         NaN
2016-07-15 22:00:00+00:00                         NaN
2016-07-15 23:00:00+00:00                         NaN

                           DE_KN_residential2_grid_import  ...  \
utc_timestamp                                              ...
2016-07-15 00:00:00+00:00                        2843.458  ...
2016-07-15 01:00:00+00:00                        2843.598  ...
2016-07-15 02:00:00+00:00                        2843.738  ...
2016-07-15 03:00:00+00:00                        2843.928  ...
2016-07-15 04:00:00+00:00                        2844.148  ...
2016-07-15 05:00:00+00:00                        2844.358  ...
2016-07-15 06:00:00+00:00                        2844.893  ...
2016-07-15 07:00:00+00:00                        2846.178  ...
2016-07-15 08:00:00+00:00                        2846.508  ...
2016-07-15 09:00:00+00:00                        2846.718  ...
2016-07-15 10:00:00+00:00                        2847.048  ...
2016-07-15 11:00:00+00:00                        2847.258  ...
2016-07-15 12:00:00+00:00                        2847.598  ...
2016-07-15 13:00:00+00:00                        2847.718  ...
2016-07-15 14:00:00+00:00                        2847.878  ...
2016-07-15 15:00:00+00:00                        2848.078  ...
2016-07-15 16:00:00+00:00                        2848.238  ...
2016-07-15 17:00:00+00:00                        2848.388  ...
2016-07-15 18:00:00+00:00                        2848.528  ...
2016-07-15 19:00:00+00:00                        2848.625  ...
2016-07-15 20:00:00+00:00                        2848.908  ...
2016-07-15 21:00:00+00:00                        2849.008  ...
2016-07-15 22:00:00+00:00                        2849.148  ...
2016-07-15 23:00:00+00:00                        2849.292  ...

                           DE_KN_residential5_grid_import  \
utc_timestamp
2016-07-15 00:00:00+00:00                        1971.904
2016-07-15 01:00:00+00:00                        1972.024
2016-07-15 02:00:00+00:00                        1972.104
2016-07-15 03:00:00+00:00                        1972.191
2016-07-15 04:00:00+00:00                        1972.314
2016-07-15 05:00:00+00:00                        1972.471
2016-07-15 06:00:00+00:00                        1972.694
2016-07-15 07:00:00+00:00                        1973.124
2016-07-15 08:00:00+00:00                        1973.254
2016-07-15 09:00:00+00:00                        1973.914
2016-07-15 10:00:00+00:00                        1974.001
2016-07-15 11:00:00+00:00                        1974.284
2016-07-15 12:00:00+00:00                        1974.601
2016-07-15 13:00:00+00:00                        1974.784
2016-07-15 14:00:00+00:00                        1974.891
2016-07-15 15:00:00+00:00                        1975.064
2016-07-15 16:00:00+00:00                        1975.194
2016-07-15 17:00:00+00:00                        1975.311
2016-07-15 18:00:00+00:00                        1975.404
2016-07-15 19:00:00+00:00                        1975.544
2016-07-15 20:00:00+00:00                        1975.626
2016-07-15 21:00:00+00:00                        1976.036
2016-07-15 22:00:00+00:00                        1976.436
2016-07-15 23:00:00+00:00                        1976.754

                           DE_KN_residential5_refrigerator  \
utc_timestamp
2016-07-15 00:00:00+00:00                          248.836
2016-07-15 01:00:00+00:00                          248.891
2016-07-15 02:00:00+00:00                          248.917
2016-07-15 03:00:00+00:00                          248.949
2016-07-15 04:00:00+00:00                          249.001
2016-07-15 05:00:00+00:00                          249.062
2016-07-15 06:00:00+00:00                          249.115
2016-07-15 07:00:00+00:00                          249.143
2016-07-15 08:00:00+00:00                          249.177
2016-07-15 09:00:00+00:00                          249.286
2016-07-15 10:00:00+00:00                          249.316
2016-07-15 11:00:00+00:00                          249.360
2016-07-15 12:00:00+00:00                          249.431
2016-07-15 13:00:00+00:00                          249.527
2016-07-15 14:00:00+00:00                          249.536
2016-07-15 15:00:00+00:00                          249.593
2016-07-15 16:00:00+00:00                          249.642
2016-07-15 17:00:00+00:00                          249.675
2016-07-15 18:00:00+00:00                          249.700
2016-07-15 19:00:00+00:00                          249.765
2016-07-15 20:00:00+00:00                          249.773
2016-07-15 21:00:00+00:00                          249.801
2016-07-15 22:00:00+00:00                          249.862
2016-07-15 23:00:00+00:00                          249.888

                           DE_KN_residential5_washing_machine  \
utc_timestamp
2016-07-15 00:00:00+00:00                             149.308
2016-07-15 01:00:00+00:00                             149.308
2016-07-15 02:00:00+00:00                             149.308
2016-07-15 03:00:00+00:00                             149.308
2016-07-15 04:00:00+00:00                             149.308
2016-07-15 05:00:00+00:00                             149.308
2016-07-15 06:00:00+00:00                             149.308
2016-07-15 07:00:00+00:00                             149.308
2016-07-15 08:00:00+00:00                             149.308
2016-07-15 09:00:00+00:00                             149.308
2016-07-15 10:00:00+00:00                             149.308
2016-07-15 11:00:00+00:00                             149.308
2016-07-15 12:00:00+00:00                             149.308
2016-07-15 13:00:00+00:00                             149.308
2016-07-15 14:00:00+00:00                             149.308
2016-07-15 15:00:00+00:00                             149.308
2016-07-15 16:00:00+00:00                             149.308
2016-07-15 17:00:00+00:00                             149.308
2016-07-15 18:00:00+00:00                             149.308
2016-07-15 19:00:00+00:00                             149.308
2016-07-15 20:00:00+00:00                             149.308
2016-07-15 21:00:00+00:00                             149.308
2016-07-15 22:00:00+00:00                             149.308
2016-07-15 23:00:00+00:00                             149.308

                           DE_KN_residential6_circulation_pump  \
utc_timestamp
2016-07-15 00:00:00+00:00                              285.542
2016-07-15 01:00:00+00:00                              285.571
2016-07-15 02:00:00+00:00                              285.600
2016-07-15 03:00:00+00:00                              285.632
2016-07-15 04:00:00+00:00                              285.660
2016-07-15 05:00:00+00:00                              285.687
2016-07-15 06:00:00+00:00                              285.715
2016-07-15 07:00:00+00:00                              285.742
2016-07-15 08:00:00+00:00                              285.778
2016-07-15 09:00:00+00:00                              285.814
2016-07-15 10:00:00+00:00                              285.842
2016-07-15 11:00:00+00:00                              285.934
2016-07-15 12:00:00+00:00                              285.963

Create a PyPSA network and set the snapshots for a period of 24 h.

In [46]:
network = pypsa.Network()
timestamps = pd.date_range(start_time, periods=24, freq="h")
network.set_snapshots(timestamps)

Add the buses for the IEEE 33-bus system. The base voltage is 12.66 kV

In [47]:
for i in range(1, 34):
    network.add(
        "Bus",
        f"Bus_{i}",
        v_nom=12.66
    )

Adding the lines. Resistance (r) and reactance (x) are in Ohm. The thermal capacity (s_nom) is set high so as to not be a limiting factor

In [48]:
# (from, to, r, x)
line_data = [
    (1, 2, 0.0922, 0.047),      (2, 3, 0.493, 0.2511),      (3, 4, 0.366, 0.1864), 
    (4, 5, 0.3811, 0.1941),     (5, 6, 0.819, 0.707),       (6, 7, 0.1872, 0.6188), 
    (7, 8, 0.7114, 0.2351),     (8, 9, 1.03, 0.74),         (9, 10, 1.044, 0.74),   
    (10, 11, 0.1966, 0.065),    (11, 12, 0.3744, 0.198),    (12, 13, 1.468, 1.155),
    (13, 14, 0.5416, 0.7129),   (14, 15, 0.591, 0.526),     (15, 16, 0.7463, 0.545),
    (16, 17, 1.289, 1.721),     (17, 18, 0.732, 0.574),     (2, 19, 0.164, 0.1565),
    (19, 20, 1.5042, 1.3554),   (20, 21, 0.4095, 0.4784),   (21, 22, 0.7089, 0.9373),   
    (3, 23, 0.4512, 0.3083),    (23, 24, 0.898, 0.7091),    (24, 25, 0.896, 0.7011), 
    (6, 26, 0.203, 0.1034),     (26, 27, 0.2842, 0.1447),   (27, 28, 1.059, 0.9337), 
    (28, 29, 0.8042, 0.7006),   (29, 30, 0.5075, 0.2585),   (30, 31, 0.9744, 0.963), 
    (31, 32, 0.3105, 0.3619),   (32, 33, 0.341, 0.5302),
]

for i, (from_b, to_b, r, x) in enumerate(line_data):
    network.add(
        "Line", 
        f"Line_{from_b}-{to_b}",
        bus0=f"Bus_{from_b}",
        bus1=f"Bus_{to_b}",
        r=r,
        x=x,
        s_nom=5000
    )

Add the loads. p_set is the active power (kW) and q_set is the reactive power (kVAr)

In [49]:
load_data = [
    (100, 60), (90, 40), (120, 80), (60, 30), (60, 20),
    (200, 100), (200, 100), (60, 20), (60, 20), (45, 30),
    (60, 35), (60, 35), (120, 80), (60, 10), (60, 20),
    (60, 20), (90, 40), (90, 40), (90, 40), (90, 40),
    (90, 40), (90, 50), (420, 200), (420, 200), (60, 25),
    (60, 25), (60, 20), (120, 70), (200, 600), (150, 70),
    (210, 100), (60, 40)
]

Define all the profiles

In [50]:
# raw_load_profile = np.sin(np.linspace(0, 2 * np.pi, 24)) * 0.4 + 0.6
price_profile = np.array([50, 45, 40, 40, 42, 48, 60, 75, 70, 65, 50, 30,
                          20, 20, 25, 45, 65, 80, 90, 100, 85, 70, 60, 55])
grid_price_series = pd.Series(price_profile, index=network.snapshots)

# raw_pv_profile = np.sin(np.linspace(-np.pi / 2, 3 * np.pi / 2, 24))
# raw_pv_profile[raw_pv_profile < 0] = 0
# pv_series = pd.Series(raw_pv_profile, index=network.snapshots)

Apply the time varying profiles

In [51]:
for i, (p, q) in enumerate(load_data):

    raw_load_col_name = load_cols[i % len(load_cols)]
    raw_load = dataset_day[raw_load_col_name]
    raw_load_series = raw_load.values
    normalized_load = raw_load_series / raw_load_series.max()
    real_load_profile = normalized_load * p

    # load_profile_series = pd.Series(p * raw_load_profile, index=network.snapshots)
    network.add(
        "Load",
        f"Load_bus_{i+2}",
        bus=f"Bus_{i+2}",
        p_set=real_load_profile,
        q_set=q
    )

Add grid, PV and batteries

In [54]:
network.add(
    "Generator",
    "Substation",
    bus="Bus_1",
    p_nom=10000,
    p_min_pu=-1.0,
    carrier="gas",
    marginal_cost=grid_price_series
)

for i in range(2, 34):

    raw_pv_col = pv_cols[i % len(pv_cols)]
    raw_pv = dataset_day[raw_pv_col].fillna(0)
    raw_pv_series = raw_pv.values
    real_pv_profile = raw_pv_series / raw_pv_series.max()
    # real_pv_profile = real_pv_profile.fillna(0)

    network.add(
        "Generator",
        f"PV_bus_{i}",
        bus=f"Bus_{i}",
        p_nom=150,
        p_max_pu=real_pv_profile,
        carrier="solar",
        marginal_cost=0
    )
    network.add(
        "StorageUnit",
        f"Battery_bus_{i}",
        bus=f"Bus_{i}",
        p_nom=200, # Nominal capacity in kW
        max_hours=4, # Energy capacity is p_nom * max_hours = 800 kWh
        carrier="battery",
        efficiency_store=0.9,
        efficiency_dispatch=0.9,
        standing_loss=0.01 # 1% loss per hour
    )

WARNING:pypsa.network.io:The following generators are already defined and will be skipped (use overwrite=True to overwrite): Substation

In [55]:
network.optimize()

WARNING:pypsa.consistency:The following storage_units have carriers which are not defined:
Index(['Battery_bus_2', 'Battery_bus_3', 'Battery_bus_4', 'Battery_bus_5',
       'Battery_bus_6', 'Battery_bus_7', 'Battery_bus_8', 'Battery_bus_9',
       'Battery_bus_10', 'Battery_bus_11', 'Battery_bus_12', 'Battery_bus_13',
       'Battery_bus_14', 'Battery_bus_15', 'Battery_bus_16', 'Battery_bus_17',
       'Battery_bus_18', 'Battery_bus_19', 'Battery_bus_20', 'Battery_bus_21',
       'Battery_bus_22', 'Battery_bus_23', 'Battery_bus_24', 'Battery_bus_25',
       'Battery_bus_26', 'Battery_bus_27', 'Battery_bus_28', 'Battery_bus_29',
       'Battery_bus_30', 'Battery_bus_31', 'Battery_bus_32', 'Battery_bus_33'],
      dtype='str', name='StorageUnit')
WARNING:pypsa.consistency:The following lines have carriers which are not defined:
Index(['Line_1-2', 'Line_2-3', 'Line_3-4', 'Line_4-5', 'Line_5-6', 'Line_6-7',
       'Line_7-8', 'Line_8-9', 'Line_9-10', 'Line_10-11', 'Line_11-12',
       'Line_12-13', 'Line_13-14', 'Line_14-15', 'Line_15-16', 'Line_16-17',
       'Line_17-18', 'Line_2-19', 'Line_19-20', 'Line_20-21', 'Line_21-22',
       'Line_3-23', 'Line_23-24', 'Line_24-25', 'Line_6-26', 'Line_26-27',
       'Line_27-28', 'Line_28-29', 'Line_29-30', 'Line_30-31', 'Line_31-32',
       'Line_32-33'],
      dtype='str', name='Line')
WARNING:pypsa.consistency:The following generators have carriers which are not defined:
Index(['Substation', 'PV_bus_2', 'PV_bus_3', 'PV_bus_4', 'PV_bus_5',
       'PV_bus_6', 'PV_bus_7', 'PV_bus_8', 'PV_bus_9', 'PV_bus_10',
       'PV_bus_11', 'PV_bus_12', 'PV_bus_13', 'PV_bus_14', 'PV_bus_15',
       'PV_bus_16', 'PV_bus_17', 'PV_bus_18', 'PV_bus_19', 'PV_bus_20',
       'PV_bus_21', 'PV_bus_22', 'PV_bus_23', 'PV_bus_24', 'PV_bus_25',
       'PV_bus_26', 'PV_bus_27', 'PV_bus_28', 'PV_bus_29', 'PV_bus_30',
       'PV_bus_31', 'PV_bus_32', 'PV_bus_33'],
      dtype='str', name='Generator')
WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['Bus_1', 'Bus_2', 'Bus_3', 'Bus_4', 'Bus_5', 'Bus_6', 'Bus_7', 'Bus_8',
       'Bus_9', 'Bus_10', 'Bus_11', 'Bus_12', 'Bus_13', 'Bus_14', 'Bus_15',
       'Bus_16', 'Bus_17', 'Bus_18', 'Bus_19', 'Bus_20', 'Bus_21', 'Bus_22',
       'Bus_23', 'Bus_24', 'Bus_25', 'Bus_26', 'Bus_27', 'Bus_28', 'Bus_29',
       'Bus_30', 'Bus_31', 'Bus_32', 'Bus_33'],
      dtype='str', name='Bus')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.15s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 3864 primals, 9288 duals
Objective: -2.71e+06
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Line-fix-s-lower, Line-fix-s-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance were not assigned to the network.
c:\Users\Raluq\anaconda3\Lib\site-packages\pypsa\network\power_flow.py:1064: UserWarning: 'where' used without 'out', expect unitialized memory in output. If this is intentional, use out=None.
  self.p_branch_shift = np.multiply(-b, phase_shift, where=b != np.inf)

('ok', 'optimal')

In [56]:
print(f"cost: {network.objective:.2f}")

cost: -2706415.57

In [57]:
network.generators_t.p

Generator,Substation,PV_bus_2,PV_bus_3,PV_bus_4,PV_bus_5,PV_bus_6,PV_bus_7,PV_bus_8,PV_bus_9,PV_bus_10,...,PV_bus_24,PV_bus_25,PV_bus_26,PV_bus_27,PV_bus_28,PV_bus_29,PV_bus_30,PV_bus_31,PV_bus_32,PV_bus_33
snapshot,,,,,,,,,,,,,,,,,,,,,
2016-07-15 00:00:00,-1072.457420,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,...,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690
2016-07-15 01:00:00,1036.466106,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,...,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690
2016-07-15 02:00:00,5000.000000,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,...,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690
2016-07-15 03:00:00,5000.000000,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,...,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690,149.394052,149.401885,149.631704,149.106690
2016-07-15 04:00:00,5000.000000,149.396213,149.402134,149.632174,149.109284,149.396213,149.402134,149.632174,149.109284,149.396213,...,149.632174,149.109284,149.396213,149.402134,149.632174,149.109284,149.396213,149.402134,149.632174,149.109284
2016-07-15 05:00:00,-1071.413045,149.408650,149.411643,149.637713,149.124593,149.408650,149.411643,149.637713,149.124593,149.408650,...,149.637713,149.124593,149.408650,149.411643,149.637713,149.124593,149.408650,149.411643,149.637713,149.124593
2016-07-15 06:00:00,-5000.000000,149.429547,149.431489,149.655548,149.163499,149.429547,149.431489,149.655548,149.163499,149.429547,...,149.655548,149.163499,149.429547,149.431489,149.655548,149.163499,149.429547,149.431489,149.655548,149.163499
2016-07-15 07:00:00,-5000.000000,149.481536,149.477577,149.693188,149.244789,149.481536,149.477577,149.693188,149.244789,149.481536,...,149.693188,149.244789,149.481536,149.477577,149.693188,149.244789,149.481536,149.477577,149.693188,149.244789
2016-07-15 08:00:00,-5000.000000,149.569490,149.566526,149.762752,149.394465,149.569490,149.566526,149.762752,149.394465,149.569490,...,149.762752,149.394465,149.569490,149.566526,149.762752,149.394465,149.569490,149.566526,149.762752,149.394465
2016-07-15 09:00:00,-5000.000000,149.643212,149.622509,149.810047,149.492709,149.643212,149.622509,149.810047,149.492709,149.643212,...,149.810047,149.492709,149.643212,149.622509,149.810047,149.492709,149.643212,149.622509,149.810047,149.492709
2016-07-15 10:00:00,-1079.061773,149.681032,149.664406,149.837638,149.560589,149.681032,149.664406,149.837638,149.560589,149.681032,...,149.837638,149.560589,149.681032,149.664406,149.837638,149.560589,149.681032,149.664406,149.837638,149.560589
2016-07-15 11:00:00,5000.000000,149.778384,149.787894,149.887486,149.687111,149.778384,149.787894,149.887486,149.687111,149.778384,...,149.887486,149.687111,149.778384,149.787894,149.887486,149.687111,149.778384,149.787894,149.887486,149.687111
2016-07-15 12:00:00,5000.000000,149.842300,149.851291,149.926054,149.770299,149.842300,149.851291,149.926054,149.770299,149.842300,...,149.926054,149.770299,149.842300,149.851291,149.926054,149.770299,149.842300,149.851291,149.926054,149.770299
2016-07-15 13:00:00,5000.000000,149.885318,149.897158,149.944321,149.846718,149.885318,149.897158,149.944321,149.846718,149.885318,...,149.944321,149.846718,149.885318,149.897158,149.944321,149.846718,149.885318,149.897158,149.944321,149.846718
2016-07-15 14:00:00,5000.000000,149.921099,149.928058,149.966870,149.893152,149.921099,149.928058,149.966870,149.893152,149.921099,...,149.966870,149.893152,149.921099,149.928058,149.966870,149.893152,149.921099,149.928058,149.966870,149.893152
2016-07-15 15:00:00,3624.970234,149.961263,149.967612,149.985671,149.949012,149.961263,149.967612,149.985671,149.949012,149.961263,...,149.985671,149.949012,149.961263,149.967612,149.985671,149.949012,149.961263,149.967612,149.985671,149.949012
2016-07-15 16:00:00,-3728.758233,149.974617,149.979603,149.991235,149.968496,149.974617,149.979603,149.991235,149.968496,149.974617,...,149.991235,149.968496,149.974617,149.979603,149.991235,149.968496,149.974617,149.979603,149.991235,149.968496
2016-07-15 17:00:00,-5000.000000,149.994495,149.996554,149.998399,149.993294,149.994495,149.996554,149.998399,149.993294,149.994495,...,149.998399,149.993294,149.994495,149.996554,149.998399,149.993294,149.994495,149.996554,149.998399,149.993294
2016-07-15 18:00:00,-5000.000000,149.999796,150.000000,149.999975,150.000000,149.999796,150.000000,149.999975,150.000000,149.999796,...,149.999975,150.000000,149.999796,150.000000,149.999975,150.000000,149.999796,150.000000,149.999975,150.000000
2016-07-15 19:00:00,-5000.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,...,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
2016-07-15 20:00:00,-5000.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,...,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
2016-07-15 21:00:00,-5000.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,...,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
2016-07-15 22:00:00,-1085.535512,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,...,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000
2016-07-15 23:00:00,-1085.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,...,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000,150.000000

In [58]:
network.storage_units_t.p

StorageUnit,Battery_bus_2,Battery_bus_3,Battery_bus_4,Battery_bus_5,Battery_bus_6,Battery_bus_7,Battery_bus_8,Battery_bus_9,Battery_bus_10,Battery_bus_11,...,Battery_bus_24,Battery_bus_25,Battery_bus_26,Battery_bus_27,Battery_bus_28,Battery_bus_29,Battery_bus_30,Battery_bus_31,Battery_bus_32,Battery_bus_33
snapshot,,,,,,,,,,,,,,,,,,,,,
2016-07-15 00:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-07-15 01:00:00,-200.000000,-200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-200.000000,0.000000,0.000000,-174.606623,0.000000,-151.575893,0.000000,0.000000,0.000000,0.000000
2016-07-15 02:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-71.883652,0.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2016-07-15 03:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,0.000000,-71.568114,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2016-07-15 04:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-145.449944,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-117.493706,-117.545374,-200.000000
2016-07-15 05:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-07-15 06:00:00,200.000000,200.000000,200.000000,200.000000,65.500179,63.438959,110.331943,64.834001,200.000000,18.092098,...,200.000000,200.000000,200.000000,200.000000,61.398351,200.000000,200.000000,0.000000,200.000000,0.000000
2016-07-15 07:00:00,200.000000,200.000000,66.845178,200.000000,200.000000,200.000000,0.000000,0.000000,0.000000,0.000000,...,200.000000,0.000000,66.845178,200.000000,0.000000,200.000000,200.000000,200.000000,0.000000,60.784368
2016-07-15 08:00:00,200.000000,17.151110,200.000000,68.176726,200.000000,0.000000,200.000000,0.000000,0.000000,200.000000,...,17.151110,64.156524,200.000000,200.000000,200.000000,0.000000,0.000000,200.000000,0.000000,200.000000
2016-07-15 09:00:00,18.979599,200.000000,0.000000,0.000000,0.000000,200.000000,0.000000,200.000000,112.520372,200.000000,...,200.000000,200.000000,0.000000,0.000000,200.000000,180.786298,67.494959,0.000000,200.000000,200.000000
2016-07-15 10:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-07-15 11:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-104.944314,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-141.605792,-200.000000,-200.000000,-200.000000,-130.260043
2016-07-15 12:00:00,-105.894870,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2016-07-15 13:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-164.068085,-200.000000,-106.835922,-200.000000,-200.000000
2016-07-15 14:00:00,-200.000000,-200.000000,-107.767563,-200.000000,-200.000000,-200.000000,-107.767563,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-128.531365,-200.000000
2016-07-15 15:00:00,-200.000000,-108.689887,-200.000000,-108.689887,-200.000000,-108.689887,-200.000000,-108.689887,-108.689887,-108.689887,...,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-200.000000,-108.689887,-200.000000,-179.443835,-175.681811
2016-07-15 16:00:00,200.000000,200.000000,94.413088,0.000000,0.000000,0.000000,200.000000,0.000000,0.000000,46.919625,...,200.000000,200.000000,0.000000,0.000000,200.000000,100.596957,0.000000,200.000000,0.000000,0.000000
2016-07-15 17:00:00,0.000000,97.447727,0.000000,0.000000,200.000000,200.000000,200.000000,164.687873,200.000000,200.000000,...,0.000000,0.000000,200.000000,89.325696,200.000000,200.000000,200.000000,200.000000,87.285088,93.468957
2016-07-15 18:00:00,200.000000,200.000000,200.000000,86.412237,200.000000,90.432439,0.000000,0.000000,0.000000,0.000000,...,200.000000,136.059918,200.000000,200.000000,0.000000,200.000000,200.000000,0.000000,0.000000,200.000000
2016-07-15 19:00:00,200.000000,0.000000,200.000000,200.000000,0.000000,0.000000,0.000000,200.000000,89.528115,44.002050,...,200.000000,200.000000,0.000000,0.000000,120.792816,200.000000,200.000000,0.000000,200.000000,200.000000
2016-07-15 20:00:00,0.000000,0.000000,200.000000,200.000000,92.612834,200.000000,96.513632,200.000000,200.000000,200.000000,...,98.573634,161.241309,92.612834,200.000000,178.948947,0.000000,96.633036,200.000000,200.000000,200.000000
2016-07-15 21:00:00,97.587898,200.000000,0.000000,200.000000,200.000000,200.000000,200.000000,125.647194,200.000000,200.000000,...,0.000000,0.000000,200.000000,200.000000,0.000000,0.000000,0.000000,97.548496,200.000000,0.000000
2016-07-15 22:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2016-07-15 23:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000