In [23]:
import pypsa
import pandas as pd
import numpy as np

In [34]:
raw_2 = pd.read_csv("household_data_60min_singleindex.csv")
print("a")

a

In [ ]:
raw_dataset = pd.read_csv("household_data_60min_singleindex.csv",
                          parse_dates=["utc_timestamp"],
                          index_col="utc_timestamp")


start_time = "2016-07-15 00:00:00"
end_time = "2016-07-15 23:00:00"
dataset_day = raw_dataset.loc[start_time:end_time]
print(dataset_day)

load_cols = [col for col in dataset_day.columns if "grid_import" in col and "residential" in col]
pv_cols = [col for col in dataset_day.columns if "pv" in col and "residential" in col]

if (len(load_cols) == 0 or len(pv_cols) == 0):
    raise ValueError("Could not find consumption or solar columns")

print(f"Found {len(load_cols)} loads and {len(pv_cols)} pv")

                                 cet_cest_timestamp  \
utc_timestamp
2016-07-15 00:00:00+00:00  2016-07-15T02:00:00+0200
2016-07-15 01:00:00+00:00  2016-07-15T03:00:00+0200
2016-07-15 02:00:00+00:00  2016-07-15T04:00:00+0200
2016-07-15 03:00:00+00:00  2016-07-15T05:00:00+0200
2016-07-15 04:00:00+00:00  2016-07-15T06:00:00+0200
2016-07-15 05:00:00+00:00  2016-07-15T07:00:00+0200
2016-07-15 06:00:00+00:00  2016-07-15T08:00:00+0200
2016-07-15 07:00:00+00:00  2016-07-15T09:00:00+0200
2016-07-15 08:00:00+00:00  2016-07-15T10:00:00+0200
2016-07-15 09:00:00+00:00  2016-07-15T11:00:00+0200
2016-07-15 10:00:00+00:00  2016-07-15T12:00:00+0200
2016-07-15 11:00:00+00:00  2016-07-15T13:00:00+0200
2016-07-15 12:00:00+00:00  2016-07-15T14:00:00+0200
2016-07-15 13:00:00+00:00  2016-07-15T15:00:00+0200
2016-07-15 14:00:00+00:00  2016-07-15T16:00:00+0200
2016-07-15 15:00:00+00:00  2016-07-15T17:00:00+0200
2016-07-15 16:00:00+00:00  2016-07-15T18:00:00+0200
2016-07-15 17:00:00+00:00  2016-07-15T19:00:00+0200
2016-07-15 18:00:00+00:00  2016-07-15T20:00:00+0200
2016-07-15 19:00:00+00:00  2016-07-15T21:00:00+0200
2016-07-15 20:00:00+00:00  2016-07-15T22:00:00+0200
2016-07-15 21:00:00+00:00  2016-07-15T23:00:00+0200
2016-07-15 22:00:00+00:00  2016-07-16T00:00:00+0200
2016-07-15 23:00:00+00:00  2016-07-16T01:00:00+0200

                           DE_KN_industrial1_grid_import  \
utc_timestamp
2016-07-15 00:00:00+00:00                     105162.547
2016-07-15 01:00:00+00:00                     105219.086
2016-07-15 02:00:00+00:00                     105272.273
2016-07-15 03:00:00+00:00                     105309.078
2016-07-15 04:00:00+00:00                     105360.984
2016-07-15 05:00:00+00:00                     105407.164
2016-07-15 06:00:00+00:00                     105476.516
2016-07-15 07:00:00+00:00                     105538.312
2016-07-15 08:00:00+00:00                     105605.406
2016-07-15 09:00:00+00:00                     105675.320
2016-07-15 10:00:00+00:00                     105756.070
2016-07-15 11:00:00+00:00                     105823.320
2016-07-15 12:00:00+00:00                     105922.969
2016-07-15 13:00:00+00:00                     106026.773
2016-07-15 14:00:00+00:00                     106119.797
2016-07-15 15:00:00+00:00                     106215.531
2016-07-15 16:00:00+00:00                     106312.766
2016-07-15 17:00:00+00:00                     106384.594
2016-07-15 18:00:00+00:00                     106460.516
2016-07-15 19:00:00+00:00                     106529.555
2016-07-15 20:00:00+00:00                     106605.336
2016-07-15 21:00:00+00:00                     106671.273
2016-07-15 22:00:00+00:00                     106727.820
2016-07-15 23:00:00+00:00                     106789.133

                           DE_KN_industrial1_pv_1  DE_KN_industrial1_pv_2  \
utc_timestamp
2016-07-15 00:00:00+00:00                2920.822                2540.064
2016-07-15 01:00:00+00:00                2920.822                2540.064
2016-07-15 02:00:00+00:00                2920.822                2540.064
2016-07-15 03:00:00+00:00                2920.822                2540.064
2016-07-15 04:00:00+00:00                2920.842                2540.064
2016-07-15 05:00:00+00:00                2921.127                2540.191
2016-07-15 06:00:00+00:00                2921.572                2540.548
2016-07-15 07:00:00+00:00                2922.742                2541.653
2016-07-15 08:00:00+00:00                2924.795                2543.721
2016-07-15 09:00:00+00:00                2927.077                2545.979
2016-07-15 10:00:00+00:00                2928.012                2546.728
2016-07-15 11:00:00+00:00                2930.462                2548.779
2016-07-15 12:00:00+00:00                2932.115                2550.171
2016-07-15 13:00:00+00:00                2933.110                2550.984
2016-07-15 14:00:00+00:00                2933.837                2551.541
2016-07-15 15:00:00+00:00                2934.857                2552.378
2016-07-15 16:00:00+00:00                2935.197                2552.591
2016-07-15 17:00:00+00:00                2935.655                2552.976
2016-07-15 18:00:00+00:00                2935.762                2553.013
2016-07-15 19:00:00+00:00                2935.762                2553.013
2016-07-15 20:00:00+00:00                2935.762                2553.013
2016-07-15 21:00:00+00:00                2935.762                2553.013
2016-07-15 22:00:00+00:00                2935.762                2553.013
2016-07-15 23:00:00+00:00                2935.762                2553.013

                           DE_KN_industrial2_grid_import  \
utc_timestamp
2016-07-15 00:00:00+00:00                       4271.209
2016-07-15 01:00:00+00:00                       4272.680
2016-07-15 02:00:00+00:00                       4274.115
2016-07-15 03:00:00+00:00                       4275.590
2016-07-15 04:00:00+00:00                       4277.100
2016-07-15 05:00:00+00:00                       4279.500
2016-07-15 06:00:00+00:00                       4280.234
2016-07-15 07:00:00+00:00                       4280.324
2016-07-15 08:00:00+00:00                       4280.355
2016-07-15 09:00:00+00:00                       4280.453
2016-07-15 10:00:00+00:00                       4280.543
2016-07-15 11:00:00+00:00                       4280.723
2016-07-15 12:00:00+00:00                       4280.785
2016-07-15 13:00:00+00:00                       4280.840
2016-07-15 14:00:00+00:00                       4281.703
2016-07-15 15:00:00+00:00                       4282.168
2016-07-15 16:00:00+00:00                       4283.113
2016-07-15 17:00:00+00:00                       4283.383
2016-07-15 18:00:00+00:00                       4285.283
2016-07-15 19:00:00+00:00                       4287.975
2016-07-15 20:00:00+00:00                       4289.539
2016-07-15 21:00:00+00:00                       4291.174
2016-07-15 22:00:00+00:00                       4292.799
2016-07-15 23:00:00+00:00                       4294.439

                           DE_KN_industrial2_pv  \
utc_timestamp
2016-07-15 00:00:00+00:00             11795.706
2016-07-15 01:00:00+00:00             11795.706
2016-07-15 02:00:00+00:00             11795.706
2016-07-15 03:00:00+00:00             11795.706
2016-07-15 04:00:00+00:00             11795.866
2016-07-15 05:00:00+00:00             11796.875
2016-07-15 06:00:00+00:00             11798.897
2016-07-15 07:00:00+00:00             11803.561
2016-07-15 08:00:00+00:00             11812.327
2016-07-15 09:00:00+00:00             11817.327
2016-07-15 10:00:00+00:00             11821.377
2016-07-15 11:00:00+00:00             11830.077
2016-07-15 12:00:00+00:00             11835.346
2016-07-15 13:00:00+00:00             11839.420
2016-07-15 14:00:00+00:00             11841.786
2016-07-15 15:00:00+00:00             11845.176
2016-07-15 16:00:00+00:00             11846.381
2016-07-15 17:00:00+00:00             11847.926
2016-07-15 18:00:00+00:00             11848.381
2016-07-15 19:00:00+00:00             11848.397
2016-07-15 20:00:00+00:00             11848.397
2016-07-15 21:00:00+00:00             11848.397
2016-07-15 22:00:00+00:00             11848.397
2016-07-15 23:00:00+00:00             11848.397

                           DE_KN_industrial2_storage_charge  \
utc_timestamp
2016-07-15 00:00:00+00:00                           375.183
2016-07-15 01:00:00+00:00                           375.205
2016-07-15 02:00:00+00:00                           375.225
2016-07-15 03:00:00+00:00                           375.246
2016-07-15 04:00:00+00:00                           375.266
2016-07-15 05:00:00+00:00                           375.286
2016-07-15 06:00:00+00:00                           375.311
2016-07-15 07:00:00+00:00                           376.133
2016-07-15 08:00:00+00:00                           377.377
2016-07-15 09:00:00+00:00                           377.860
2016-07-15 10:00:00+00:00                           378.384
2016-07-15 11:00:00+00:00                           379.163
2016-07-15 12:00:00+00:00                           379.928
2016-07-15 13:00:00+00:00                           380.285
2016-07-15 14:00:00+00:00                           380.588
2016-07-15 15:00:00+00:00                           380.967
2016-07-15 16:00:00+00:00                           380.967
2016-07-15 17:00:00+00:00                           381.034
2016-07-15 18:00:00+00:00                           381.047
2016-07-15 19:00:00+00:00                           381.068
2016-07-15 20:00:00+00:00                           381.088
2016-07-15 21:00:00+00:00                           381.108
2016-07-15 22:00:00+00:00                           381.129
2016-07-15 23:00:00+00:00                           381.150

                           DE_KN_industrial2_storage_decharge  \
utc_timestamp
2016-07-15 00:00:00+00:00                             234.460
2016-07-15 01:00:00+00:00                             234.470
2016-07-15 02:00:00+00:00                             234.470
2016-07-15 03:00:00+00:00                             234.470
2016-07-15 04:00:00+00:00                             234.470
2016-07-15 05:00:00+00:00                             234.470
2016-07-15 06:00:00+00:00                             234.482
2016-07-15 07:00:00+00:00                             234.500
2016-07-15 08:00:00+00:00                             234.536
2016-07-15 09:00:00+00:00                             234.756
2016-07-15 10:00:00+00:00                             235.073
2016-07-15 11:00:00+00:00                             235.281
2016-07-15 12:00:00+00:00                             235.351
2016-07-15 13:00:00+00:00                             235.549
2016-07-15 14:00:00+00:00                             236.192
2016-07-15 15:00:00+00:00                             236.689
2016-07-15 16:00:00+00:00                             237.570
2016-07-15 17:00:00+00:00                             238.035
2016-07-15 18:00:00+00:00                             238.273
2016-07-15 19:00:00+00:00                             238.273
2016-07-15 20:00:00+00:00                             238.273
2016-07-15 21:00:00+00:00                             238.273
2016-07-15 22:00:00+00:00                             238.273
2016-07-15 23:00:00+00:00                             238.273

                           DE_KN_industrial3_area_offices  \
utc_timestamp
2016-07-15 00:00:00+00:00                        7877.314
2016-07-15 01:00:00+00:00                        7878.125
2016-07-15 02:00:00+00:00                        7878.955
2016-07-15 03:00:00+00:00                        7879.785
2016-07-15 04:00:00+00:00                        7880.705
2016-07-15 05:00:00+00:00                        7881.540
2016-07-15 06:00:00+00:00                        7883.254
2016-07-15 07:00:00+00:00                        7885.104
2016-07-15 08:00:00+00:00                        7886.824
2016-07-15 09:00:00+00:00                        7888.635
2016-07-15 10:00:00+00:00                        7891.149
2016-07-15 11:00:00+00:00                        7893.414
2016-07-15 12:00:00+00:00                        7894.850
2016-07-15 13:00:00+00:00                        7896.290
2016-07-15 14:00:00+00:00                        7897.644
2016-07-15 15:00:00+00:00                        7898.764
2016-07-15 16:00:00+00:00                        7899.839
2016-07-15 17:00:00+00:00                        7900.729
2016-07-15 18:00:00+00:00                        7901.834
2016-07-15 19:00:00+00:00                        7903.329
2016-07-15 20:00:00+00:00                        7904.179
2016-07-15 21:00:00+00:00                        7905.014
2016-07-15 22:00:00+00:00                        7905.800
2016-07-15 23:00:00+00:00                        7906.589

                           DE_KN_industrial3_area_room_1  ...  \
utc_timestamp                                             ...
2016-07-15 00:00:00+00:00                       2965.089  ...
2016-07-15 01:00:00+00:00                       2965.263  ...
2016-07-15 02:00:00+00:00                       2965.444  ...
2016-07-15 03:00:00+00:00                       2965.623  ...
2016-07-15 04:00:00+00:00                       2965.799  ...
2016-07-15 05:00:00+00:00                       2965.973  ...
2016-07-15 06:00:00+00:00                       2966.148  ...
2016-07-15 07:00:00+00:00                       2966.324  ...
2016-07-15 08:00:00+00:00                       2966.499  ...
2016-07-15 09:00:00+00:00                       2966.674  ...
2016-07-15 10:00:00+00:00                       2966.853  ...
2016-07-15 11:00:00+00:00                       2967.033  ...
2016-07-15 12:00:00+00:00                       2967.214  ...
2016-07-15 13:00:00+00:00                       2967.393  ...
2016-07-15 14:00:00+00:00                       2967.564  ...
2016-07-15 15:00:00+00:00                       2967.743  ...
2016-07-15 16:00:00+00:00                       2967.913  ...
2016-07-15 17:00:00+00:00                       2968.089  ...
2016-07-15 18:00:00+00:00                       2968.263  ...
2016-07-15 19:00:00+00:00                       2968.444  ...
2016-07-15 20:00:00+00:00                       2968.618  ...
2016-07-15 21:00:00+00:00                       2968.794  ...
2016-07-15 22:00:00+00:00                       2968.973  ...
2016-07-15 23:00:00+00:00                       2969.154  ...

                           DE_KN_residential5_refrigerator  \
utc_timestamp
2016-07-15 00:00:00+00:00                          248.836
2016-07-15 01:00:00+00:00                          248.891
2016-07-15 02:00:00+00:00                          248.917
2016-07-15 03:00:00+00:00                          248.949
2016-07-15 04:00:00+00:00                          249.001
2016-07-15 05:00:00+00:00                          249.062
2016-07-15 06:00:00+00:00                          249.115
2016-07-15 07:00:00+00:00                          249.143
2016-07-15 08:00:00+00:00                          249.177
2016-07-15 09:00:00+00:00                          249.286
2016-07-15 10:00:00+00:00                          249.316
2016-07-15 11:00:00+00:00                          249.360
2016-07-15 12:00:00+00:00                          249.431
2016-07-15 13:00:00+00:00                          249.527
2016-07-15 14:00:00+00:00                          249.536
2016-07-15 15:00:00+00:00                          249.593
2016-07-15 16:00:00+00:00                          249.642
2016-07-15 17:00:00+00:00                          249.675
2016-07-15 18:00:00+00:00                          249.700
2016-07-15 19:00:00+00:00                          249.765
2016-07-15 20:00:00+00:00                          249.773
2016-07-15 21:00:00+00:00                          249.801
2016-07-15 22:00:00+00:00                          249.862
2016-07-15 23:00:00+00:00                          249.888

                           DE_KN_residential5_washing_machine  \
utc_timestamp
2016-07-15 00:00:00+00:00                             149.308
2016-07-15 01:00:00+00:00                             149.308
2016-07-15 02:00:00+00:00                             149.308
2016-07-15 03:00:00+00:00                             149.308
2016-07-15 04:00:00+00:00                             149.308
2016-07-15 05:00:00+00:00                             149.308
2016-07-15 06:00:00+00:00                             149.308
2016-07-15 07:00:00+00:00                             149.308
2016-07-15 08:00:00+00:00                             149.308
2016-07-15 09:00:00+00:00                             149.308
2016-07-15 10:00:00+00:00                             149.308
2016-07-15 11:00:00+00:00                             149.308
2016-07-15 12:00:00+00:00                             149.308
2016-07-15 13:00:00+00:00                             149.308
2016-07-15 14:00:00+00:00                             149.308
2016-07-15 15:00:00+00:00                             149.308
2016-07-15 16:00:00+00:00                             149.308
2016-07-15 17:00:00+00:00                             149.308
2016-07-15 18:00:00+00:00                             149.308
2016-07-15 19:00:00+00:00                             149.308
2016-07-15 20:00:00+00:00                             149.308
2016-07-15 21:00:00+00:00                             149.308
2016-07-15 22:00:00+00:00                             149.308
2016-07-15 23:00:00+00:00                             149.308

                           DE_KN_residential6_circulation_pump  \
utc_timestamp
2016-07-15 00:00:00+00:00                              285.542
2016-07-15 01:00:00+00:00                              285.571
2016-07-15 02:00:00+00:00                              285.600
2016-07-15 03:00:00+00:00                              285.632
2016-07-15 04:00:00+00:00                              285.660
2016-07-15 05:00:00+00:00                              285.687
2016-07-15 06:00:00+00:00                              285.715
2016-07-15 07:00:00+00:00                              285.742
2016-07-15 08:00:00+00:00                              285.778
2016-07-15 09:00:00+00:00                              285.814
2016-07-15 10:00:00+00:00                              285.842
2016-07-15 11:00:00+00:00                              285.934
2016-07-15 12:00:00+00:00                              285.963
2016-07-15 13:00:00+00:00                              286.010
2016-07-15 14:00:00+00:00                              286.043
2016-07-15 15:00:00+00:00                              286.073
2016-07-15 16:00:00+00:00                              286.102
2016-07-15 17:00:00+00:00                              286.134
2016-07-15 18:00:00+00:00                              286.164
2016-07-15 19:00:00+00:00                              286.192
2016-07-15 20:00:00+00:00                              286.221
2016-07-15 21:00:00+00:00                              286.250
2016-07-15 22:00:00+00:00                              286.278
2016-07-15 23:00:00+00:00                              286.307

                           DE_KN_residential6_dishwasher  \
utc_timestamp
2016-07-15 00:00:00+00:00                         40.347
2016-07-15 01:00:00+00:00                         40.348
2016-07-15 02:00:00+00:00                         40.348
2016-07-15 03:00:00+00:00                         40.402
2016-07-15 04:00:00+00:00                         40.430
2016-07-15 05:00:00+00:00                         40.444
2016-07-15 06:00:00+00:00                         40.446
2016-07-15 07:00:00+00:00                         40.447
2016-07-15 08:00:00+00:00                         40.447
2016-07-15 09:00:00+00:00                         40.447
2016-07-15 10:00:00+00:00                         40.447
2016-07-15 11:00:00+00:00                         40.448
2016-07-15 12:00:00+00:00                         40.448
2016-07-15 13:00:00+00:00                         40.448
2016-07-15 14:00:00+00:00                         40.492
2016-07-15 15:00:00+00:00                         40.505
2016-07-15 16:00:00+00:00                         40.534
2016-07-15 17:00:00+00:00                         40.547
2016-07-15 18:00:00+00:00                         40.553
2016-07-15 19:00:00+00:00                         40.553
2016-07-15 20:00:00+00:00                         40.553
2016-07-15 21:00:00+00:00                         40.554
2016-07-15 22:00:00+00:00                         40.554
2016-07-15 23:00:00+00:00                         40.554

                           DE_KN_residential6_freezer  \
utc_timestamp
2016-07-15 00:00:00+00:00                      95.619
2016-07-15 01:00:00+00:00                      95.620
2016-07-15 02:00:00+00:00                      95.621
2016-07-15 03:00:00+00:00                      95.622
2016-07-15 04:00:00+00:00                      95.623
2016-07-15 05:00:00+00:00                      95.624

Create a PyPSA network and set the snapshots for a period of 24 h.

In [25]:
network = pypsa.Network()
timestamps = pd.date_range(start_time, periods=24, freq="h")
network.set_snapshots(timestamps)

Add the buses for the IEEE 33-bus system. The base voltage is 12.66 kV

In [26]:
for i in range(1, 34):
    network.add(
        "Bus",
        f"Bus_{i}",
        v_nom=12.66
    )

Adding the lines. Resistance (r) and reactance (x) are in Ohm. The thermal capacity (s_nom) is set high so as to not be a limiting factor

In [27]:
# (from, to, r, x)
line_data = [
    (1, 2, 0.0922, 0.047),      (2, 3, 0.493, 0.2511),      (3, 4, 0.366, 0.1864), 
    (4, 5, 0.3811, 0.1941),     (5, 6, 0.819, 0.707),       (6, 7, 0.1872, 0.6188), 
    (7, 8, 0.7114, 0.2351),     (8, 9, 1.03, 0.74),         (9, 10, 1.044, 0.74),   
    (10, 11, 0.1966, 0.065),    (11, 12, 0.3744, 0.198),    (12, 13, 1.468, 1.155),
    (13, 14, 0.5416, 0.7129),   (14, 15, 0.591, 0.526),     (15, 16, 0.7463, 0.545),
    (16, 17, 1.289, 1.721),     (17, 18, 0.732, 0.574),     (2, 19, 0.164, 0.1565),
    (19, 20, 1.5042, 1.3554),   (20, 21, 0.4095, 0.4784),   (21, 22, 0.7089, 0.9373),   
    (3, 23, 0.4512, 0.3083),    (23, 24, 0.898, 0.7091),    (24, 25, 0.896, 0.7011), 
    (6, 26, 0.203, 0.1034),     (26, 27, 0.2842, 0.1447),   (27, 28, 1.059, 0.9337), 
    (28, 29, 0.8042, 0.7006),   (29, 30, 0.5075, 0.2585),   (30, 31, 0.9744, 0.963), 
    (31, 32, 0.3105, 0.3619),   (32, 33, 0.341, 0.5302),
]

for i, (from_b, to_b, r, x) in enumerate(line_data):
    network.add(
        "Line", 
        f"Line_{from_b}-{to_b}",
        bus0=f"Bus_{from_b}",
        bus1=f"Bus_{to_b}",
        r=r,
        x=x,
        s_nom=5000
    )

Add the loads. p_set is the active power (kW) and q_set is the reactive power (kVAr)

In [28]:
load_data = [
    (100, 60), (90, 40), (120, 80), (60, 30), (60, 20),
    (200, 100), (200, 100), (60, 20), (60, 20), (45, 30),
    (60, 35), (60, 35), (120, 80), (60, 10), (60, 20),
    (60, 20), (90, 40), (90, 40), (90, 40), (90, 40),
    (90, 40), (90, 50), (420, 200), (420, 200), (60, 25),
    (60, 25), (60, 20), (120, 70), (200, 600), (150, 70),
    (210, 100), (60, 40)
]

Define all the profiles

In [29]:
# raw_load_profile = np.sin(np.linspace(0, 2 * np.pi, 24)) * 0.4 + 0.6
price_profile = np.array([50, 45, 40, 40, 42, 48, 60, 75, 70, 65, 50, 30,
                          20, 20, 25, 45, 65, 80, 90, 100, 85, 70, 60, 55])
grid_price_series = pd.Series(price_profile, index=network.snapshots)

# raw_pv_profile = np.sin(np.linspace(-np.pi / 2, 3 * np.pi / 2, 24))
# raw_pv_profile[raw_pv_profile < 0] = 0
# pv_series = pd.Series(raw_pv_profile, index=network.snapshots)

Apply the time varying profiles

In [31]:
for i, (p, q) in enumerate(load_data):

    raw_load_col = load_cols[i % len(load_cols)]
    raw_load_series = dataset_day[raw_load_col]
    normalized_load = raw_load_series / raw_load_series.max()
    real_load_profile = normalized_load * p

    # load_profile_series = pd.Series(p * raw_load_profile, index=network.snapshots)
    network.add(
        "Load",
        f"Load_bus_{i+2}",
        bus=f"Bus_{i+2}",
        p_set=real_load_profile,
        q_set=q
    )

ValueError: Series p_set has an index which does not align with the passed network snapshots.

Add grid, PV and batteries

In [ ]:
network.add(
    "Generator",
    "Substation",
    bus="Bus_1",
    p_nom=10000,
    p_min_pu=-1.0,
    carrier="gas",
    marginal_cost=grid_price_series
)

for i in range(2, 34):

    raw_pv_col = pv_cols[i % len(pv_cols)]
    raw_pv_series = dataset_day[raw_pv_col]
    real_pv_profile = raw_pv_series / raw_pv_series.max()
    real_pv_profile = real_pv_profile.fillna(0)

    network.add(
        "Generator",
        f"PV_bus_{i}",
        bus=f"Bus_{i}",
        p_nom=150,
        p_max_pu=real_pv_profile,
        carrier="solar",
        marginal_cost=0
    )
    network.add(
        "StorageUnit",
        f"Battery_bus_{i}",
        bus=f"Bus_{i}",
        p_nom=200, # Nominal capacity in kW
        max_hours=4, # Energy capacity is p_nom * max_hours = 800 kWh
        carrier="battery",
        efficiency_store=0.9,
        efficiency_dispatch=0.9,
        standing_loss=0.01 # 1% loss per hour
    )

In [ ]:
network.optimize()

WARNING:pypsa.consistency:The following buses have carriers which are not defined:
Index(['Bus_1', 'Bus_2', 'Bus_3', 'Bus_4', 'Bus_5', 'Bus_6', 'Bus_7', 'Bus_8',
       'Bus_9', 'Bus_10', 'Bus_11', 'Bus_12', 'Bus_13', 'Bus_14', 'Bus_15',
       'Bus_16', 'Bus_17', 'Bus_18', 'Bus_19', 'Bus_20', 'Bus_21', 'Bus_22',
       'Bus_23', 'Bus_24', 'Bus_25', 'Bus_26', 'Bus_27', 'Bus_28', 'Bus_29',
       'Bus_30', 'Bus_31', 'Bus_32', 'Bus_33'],
      dtype='str', name='Bus')
WARNING:pypsa.consistency:The following lines have carriers which are not defined:
Index(['Line_1-2', 'Line_2-3', 'Line_3-4', 'Line_4-5', 'Line_5-6', 'Line_6-7',
       'Line_7-8', 'Line_8-9', 'Line_9-10', 'Line_10-11', 'Line_11-12',
       'Line_12-13', 'Line_13-14', 'Line_14-15', 'Line_15-16', 'Line_16-17',
       'Line_17-18', 'Line_2-19', 'Line_19-20', 'Line_20-21', 'Line_21-22',
       'Line_3-23', 'Line_23-24', 'Line_24-25', 'Line_6-26', 'Line_26-27',
       'Line_27-28', 'Line_28-29', 'Line_29-30', 'Line_30-31', 'Line_31-32',
       'Line_32-33'],
      dtype='str', name='Line')
WARNING:pypsa.consistency:The following generators have carriers which are not defined:
Index(['Substation', 'PV_bus_2', 'PV_bus_3', 'PV_bus_4', 'PV_bus_5',
       'PV_bus_6', 'PV_bus_7', 'PV_bus_8', 'PV_bus_9', 'PV_bus_10',
       'PV_bus_11', 'PV_bus_12', 'PV_bus_13', 'PV_bus_14', 'PV_bus_15',
       'PV_bus_16', 'PV_bus_17', 'PV_bus_18', 'PV_bus_19', 'PV_bus_20',
       'PV_bus_21', 'PV_bus_22', 'PV_bus_23', 'PV_bus_24', 'PV_bus_25',
       'PV_bus_26', 'PV_bus_27', 'PV_bus_28', 'PV_bus_29', 'PV_bus_30',
       'PV_bus_31', 'PV_bus_32', 'PV_bus_33'],
      dtype='str', name='Generator')
WARNING:pypsa.consistency:The following storage_units have carriers which are not defined:
Index(['Battery_bus_2', 'Battery_bus_3', 'Battery_bus_4', 'Battery_bus_5',
       'Battery_bus_6', 'Battery_bus_7', 'Battery_bus_8', 'Battery_bus_9',
       'Battery_bus_10', 'Battery_bus_11', 'Battery_bus_12', 'Battery_bus_13',
       'Battery_bus_14', 'Battery_bus_15', 'Battery_bus_16', 'Battery_bus_17',
       'Battery_bus_18', 'Battery_bus_19', 'Battery_bus_20', 'Battery_bus_21',
       'Battery_bus_22', 'Battery_bus_23', 'Battery_bus_24', 'Battery_bus_25',
       'Battery_bus_26', 'Battery_bus_27', 'Battery_bus_28', 'Battery_bus_29',
       'Battery_bus_30', 'Battery_bus_31', 'Battery_bus_32', 'Battery_bus_33'],
      dtype='str', name='StorageUnit')
INFO:linopy.model: Solve problem using Highs solver
INFO:linopy.io: Writing time: 0.05s
INFO:linopy.constants: Optimization successful:
Status: ok
Termination condition: optimal
Solution: 3864 primals, 9288 duals
Objective: -7.78e+03
Solver model: available
Solver message: Optimal

INFO:pypsa.optimization.optimize:The shadow-prices of the constraints Generator-fix-p-lower, Generator-fix-p-upper, Line-fix-s-lower, Line-fix-s-upper, StorageUnit-fix-p_dispatch-lower, StorageUnit-fix-p_dispatch-upper, StorageUnit-fix-p_store-lower, StorageUnit-fix-p_store-upper, StorageUnit-fix-state_of_charge-lower, StorageUnit-fix-state_of_charge-upper, StorageUnit-energy_balance were not assigned to the network.
c:\Users\Raluq\anaconda3\Lib\site-packages\pypsa\network\power_flow.py:1064: UserWarning: 'where' used without 'out', expect unitialized memory in output. If this is intentional, use out=None.
  self.p_branch_shift = np.multiply(-b, phase_shift, where=b != np.inf)

('ok', 'optimal')

In [ ]:
print(f"cost: {network.objective:.2f}")

cost: -7781.96

In [ ]:
network.generators_t.p

Generator,Substation,PV_bus_2,PV_bus_3,PV_bus_4,PV_bus_5,PV_bus_6,PV_bus_7,PV_bus_8,PV_bus_9,PV_bus_10,...,PV_bus_24,PV_bus_25,PV_bus_26,PV_bus_27,PV_bus_28,PV_bus_29,PV_bus_30,PV_bus_31,PV_bus_32,PV_bus_33
snapshot,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 01:00:00,5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 02:00:00,5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 03:00:00,5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 04:00:00,5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 05:00:00,5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 06:00:00,3383.972207,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,...,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362
2025-01-01 07:00:00,-4378.222408,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,...,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942
2025-01-01 08:00:00,-1835.635580,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,...,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048
2025-01-01 09:00:00,-556.617510,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,...,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694
2025-01-01 10:00:00,-1581.590228,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,...,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695
2025-01-01 11:00:00,4076.051100,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,...,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892
2025-01-01 12:00:00,3671.363818,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,...,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892,148.602892
2025-01-01 13:00:00,3634.361733,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,...,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695,137.581695
2025-01-01 14:00:00,3967.789119,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,...,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694,116.356694
2025-01-01 15:00:00,1724.993573,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,...,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048,86.502048
2025-01-01 16:00:00,-778.621869,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,...,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942,50.231942
2025-01-01 17:00:00,-3969.591603,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,...,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362,10.236362
2025-01-01 18:00:00,-5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 19:00:00,-5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 20:00:00,-5000.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 21:00:00,1456.898250,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 22:00:00,1828.081998,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000
2025-01-01 23:00:00,2229.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,...,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000,-0.000000

In [ ]:
network.storage_units_t.p

StorageUnit,Battery_bus_2,Battery_bus_3,Battery_bus_4,Battery_bus_5,Battery_bus_6,Battery_bus_7,Battery_bus_8,Battery_bus_9,Battery_bus_10,Battery_bus_11,...,Battery_bus_24,Battery_bus_25,Battery_bus_26,Battery_bus_27,Battery_bus_28,Battery_bus_29,Battery_bus_30,Battery_bus_31,Battery_bus_32,Battery_bus_33
snapshot,,,,,,,,,,,,,,,,,,,,,
2025-01-01 00:00:00,-133.778636,-200.000000,-200.000000,-200.000000,0.000000,0.000000,0.000000,0.000000,-200.000000,-134.702503,...,-200.000000,-200.000000,0.000000,0.000000,0.000000,0.000000,-200.000000,-200.000000,0.000000,0.000000
2025-01-01 01:00:00,-190.669558,-200.000000,-200.000000,-200.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,-200.000000,-127.151016,0.000000,0.000000,0.000000,0.000000,-127.151016,0.000000,0.000000,0.000000
2025-01-01 02:00:00,0.000000,-127.879506,0.000000,0.000000,-200.000000,-200.000000,-53.516417,0.000000,-200.000000,0.000000,...,0.000000,-200.000000,-200.000000,0.000000,0.000000,0.000000,-200.000000,0.000000,0.000000,0.000000
2025-01-01 03:00:00,-200.000000,0.000000,0.000000,0.000000,0.000000,-59.042063,0.000000,-52.981253,0.000000,-136.866190,...,0.000000,0.000000,-59.042063,0.000000,-55.021861,0.000000,0.000000,-62.982263,0.000000,-200.000000
2025-01-01 04:00:00,0.000000,0.000000,-125.334704,-125.334704,-58.451643,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,-200.000000,-200.000000,-200.000000,0.000000,0.000000,-52.451440,0.000000
2025-01-01 05:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,-200.000000,-200.000000,-122.140759,0.000000,...,0.000000,0.000000,0.000000,-53.926926,0.000000,-53.926926,0.000000,0.000000,-200.000000,-55.906926
2025-01-01 06:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-01-01 07:00:00,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
2025-01-01 08:00:00,200.000000,200.000000,200.000000,200.000000,0.000000,0.000000,0.000000,0.000000,200.000000,8.108068,...,102.479227,200.000000,0.000000,0.000000,0.000000,0.000000,200.000000,0.000000,0.000000,0.000000
2025-01-01 09:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-01-01 10:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-01-01 11:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2025-01-01 12:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2025-01-01 13:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2025-01-01 14:00:00,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,...,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000,-200.000000
2025-01-01 15:00:00,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,...,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887,-108.689887
2025-01-01 16:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-01-01 17:00:00,138.351718,200.000000,93.468957,93.468957,200.000000,93.468957,93.468957,200.000000,200.000000,200.000000,...,200.000000,93.468957,93.468957,93.468957,93.468957,93.468957,93.468957,93.468957,93.468957,200.000000
2025-01-01 18:00:00,155.566067,94.534268,200.000000,200.000000,200.000000,200.000000,200.000000,94.534268,200.000000,200.000000,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,94.534268
2025-01-01 19:00:00,200.000000,200.000000,200.000000,200.000000,95.588925,200.000000,200.000000,200.000000,95.588925,95.588925,...,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
2025-01-01 20:00:00,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,...,96.633036,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000,200.000000
2025-01-01 21:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-01-01 22:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
2025-01-01 23:00:00,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000